config/routes.rb
Test1::Application.routes.draw do
  devise_for :users

  resources :tasks

  resources :customers

  resources :projects

  root :to => "projects#index"  
end

app/models/ability.rb
class Ability
	include CanCan::Ability
	
	def initialize(user)
		user ||= User.new
		
		if user.admin?
			can :manage, :all
		else
			can :read, [Customer, Task]
			can :read, Project do |project|
				project.members.include?(user)
			end
			can :update, Project do |project|
				can?(:read, project) and user.intern? 
			end
		end
	end
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	attr_accessible :name
	
	# Associations:
	has_many :projects
	
	# Validations:
	validates_presence_of :name
	validates_uniqueness_of :name
end

app/models/project.rb
class Project < ActiveRecord::Base
	attr_accessible :name, :manager_id, :customer_id, :member_ids

	# Associations
	belongs_to :manager, :class_name => 'User'
	belongs_to :customer
	has_many :tasks
	has_and_belongs_to_many :members, :class_name => 'User',
																	  :join_table => 'users_assigned_to_projects'

	# Validations
	validates_presence_of :name, :manager_id, :customer_id
	validates_uniqueness_of :name	
end

app/models/task.rb
class Task < ActiveRecord::Base
	attr_accessible :project_id, :reported_by_id, :kind, :area, :description, 
									:priority, :state, :assigned_to_id
								
	# Associations:
	belongs_to :project
	belongs_to :reported_by, :class_name => 'User'
	belongs_to :assigned_to, :class_name => 'User'
	
	# Validations:
	validates_presence_of :project_id,
												:reported_by_id, 
												:assigned_to_id,
												:description,
												:state
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  # Associations:
  has_and_belongs_to_many :projects, :join_table => 'users_assigned_to_projects'
  
  # Handelt es sich um einen Administrator?
  def admin? 
  	self.email == 'meist@infoniqa.com'
  end
  
  # Ein interner MA?
  def intern?
  	self.email.include? '@infoniqa.com'
  end
  
  def to_s
  	self.email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_filter :authenticate_user!
  
#  rescue_from CanCan::AccessDenied do |exception|
#  	flash[:alert] = "Zugriff verweigert."
#  	redirect_to root_url
#  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  # GET /customers
  # GET /customers.xml
  def index
    @customers = Customer.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @customers }
    end
  end

  # GET /customers/1
  # GET /customers/1.xml
  def show
    @customer = Customer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @customer }
    end
  end

  # GET /customers/new
  # GET /customers/new.xml
  def new
    @customer = Customer.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @customer }
    end
  end

  # GET /customers/1/edit
  def edit
    @customer = Customer.find(params[:id])
  end

  # POST /customers
  # POST /customers.xml
  def create
    @customer = Customer.new(params[:customer])

    respond_to do |format|
      if @customer.save
        format.html { redirect_to(@customer, :notice => 'Customer was successfully created.') }
        format.xml  { render :xml => @customer, :status => :created, :location => @customer }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @customer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /customers/1
  # PUT /customers/1.xml
  def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        format.html { redirect_to(@customer, :notice => 'Customer was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @customer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.xml
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to(customers_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_and_authorize_resource
  
  # GET /projects
  # GET /projects.xml
  def index
    @projects = Project.all.select{|p| p.members.include? current_user}

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.xml
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.xml
  def new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.xml
  def create
    respond_to do |format|
      if @project.save
        format.html { redirect_to(projects_path, :notice => 'Project was successfully created.') }
        format.xml  { render :xml => @project, :status => :created, :location => @project }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.xml
  def update
    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to(projects_path, :notice => 'Project was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.xml
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to(projects_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # GET /tasks
  # GET /tasks.xml
  def index
    @tasks = Task.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.xml
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.xml
  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.xml
  def create
    @task = Task.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html { redirect_to(@task, :notice => 'Task was successfully created.') }
        format.xml  { render :xml => @task, :status => :created, :location => @task }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @task.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.xml
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to(@task, :notice => 'Task was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @task.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.xml
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to(tasks_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/customers/_form.html.erb
<%= simple_form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="inputs">
    <%= f.input :name %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<h1>Listing customers</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @customers.each do |customer| %>
  <tr>
    <td><%= customer.name %></td>
    <td><%= link_to 'Show', customer %></td>
    <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
    <td><%= link_to 'Destroy', customer, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @customer.name %>
</p>


<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="de">
<head>
  <title>Test1</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>

	<% if user_signed_in? %>
		Angemeldet als <%= current_user.email %>. Falsch? <%= link_to "Abmelden", destroy_user_session_path %>
	<% else %>
		<%= link_to "Anmelden", new_user_registration_path %>
	<% end %>

	<%= yield %>
</body>
</html>

app/views/projects/_form.html.erb
<%= simple_form_for(@project) do |f| %>
	<%= f.input :name %>
	<%= f.association :customer %>
	<%= f.association :manager %>
	<%= f.association :members, :as => :check_boxes, :collection => User.all %>
	<%= f.button :submit %>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= project.name %></td>
    <td>
    	<% if can? :read, project %>
    		<%= link_to 'Show', project %>
    	<% end %>
    </td>
    <td>
    	<% if can? :update, project %>
    		<%= link_to 'Edit', edit_project_path(project) %>
    	<% end %>
    </td>
    <td>
    	<% if can? :update, project %>
				<%= link_to 'Destroy', project, :confirm => 'Are you sure?', :method => :delete %>
    	<% end %>
    </td>
  </tr>
<% end %>
</table>

<br />

<% if can? :create, Project %>
	<%= link_to 'New Project', new_project_path %>
<% end %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @project.name %></h1>
<p>
  <b>Kunde:</b>
  <%= @project.customer.name %>
</p>
<p>
  <b>Manager:</b>
  <%= @project.manager.email %>
</p>


<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/tasks/_form.html.erb
<%= simple_form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="inputs">
    <%= f.association :project %>
    <%= f.association :reported_by %>
    <%= f.input :kind %>
    <%= f.input :area %>
    <%= f.input :description %>
    <%= f.input :priority %>
    <%= f.input :state %>
    <%= f.association :assigned_to %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <tr>
    <th>gemeldet von</th>
    <th>Art</th>
    <th>Bereich</th>
    <th>Beschreibung</th>
    <th>Prio</th>
    <th>Status</th>
    <th>Zust&auml;ndig</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= task.reported_by %></td>
    <td><%= task.kind %></td>
    <td><%= task.area %></td>
    <td><%= task.description %></td>
    <td><%= task.priority %></td>
    <td><%= task.state %></td>
    <td><%= task.assigned_to %></td>
    <td><%= link_to 'Show', task %></td>
    <td><%= link_to 'Edit', edit_task_path(task) %></td>
    <td><%= link_to 'Destroy', task, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Reported by:</b>
  <%= @task.reported_by %>
</p>

<p>
  <b>Kind:</b>
  <%= @task.kind %>
</p>

<p>
  <b>Area:</b>
  <%= @task.area %>
</p>

<p>
  <b>Description:</b>
  <%= @task.description %>
</p>

<p>
  <b>Priority:</b>
  <%= @task.priority %>
</p>

<p>
  <b>State:</b>
  <%= @task.state %>
</p>

<p>
  <b>Assigned to:</b>
  <%= @task.assigned_to_id %>
</p>


<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>